### ISSUE TITLE
How does gale handle dagger version differences when used via the dagger CLI?

### ISSUE THREAD

**Issue by gerhard** [aweris/gale#84]
When `gale` is run via the `dagger` CLI, how does it ensure compatibility with the Engine that `dagger` manages?

As you know, when a command is run via `dagger run <YOUR_COMMAND HERE>`, the `dagger` CLI provisions the Engine. So if I have `dagger v0.8.4` running locally which provisions Engine `v0.8.4`, but `gale v0.0.4` expects `v0.8.1`, could this cause issues?

---

🙇‍♂️ For the `dagger run` gif size issue, have you tried `dagger run --progress plain` ? cc @vito for more terminal recording & sharing tips.

**Comment by aweris** [comment]
> 🙇‍♂️ For the dagger run gif size issue, have you tried dagger run --progress plain ? cc @vito for more terminal recording & sharing tips.

Found the issue. `terminalizer` automatically gets screen size. If I don't drop my resolution to a minimum or adjust the screen size, it tries to generate bigger images. Adjusting the resolution helped a lot.

**Comment by aweris** [comment]
With new module structure, no need to handle this issue specifically
